version: '3.5'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    container_name: virtual-manager
    restart: always
    network_mode: bridge
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
