version: '3.5'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - '8080:8080'
    container_name: virtual-manager
    restart: always
    network_mode: bridge
    environment:
      DB_HOST: '127.0.0.1'
    depends_on:
      - database
